Before we start, let's import the library we need.

In [2]:
import numpy as np

# Definition: for-loops
The for-loop is a simple concept. Over a range of numbers or items, a for-loop will go through each number or item sequentially and terminates when it reaches the end of the range. In python, the for-loop is initialised with a `for <item> in <range>:`. The code snippet below provides a few examples.

**Note**: Unlike in many other programming languages, we want to avoid using for-loops in Python as they may be excruciatingly slow here. In future exercises, we will encounter more concrete scenarios where using a for-loop may be the easiest solution, and we will learn how to efficiently *vectorise* our code to avoid using unnecessary for-loops.

In situations such as numerical intergration over time or over dimensions, a for-loop may be unavoidable. For unavoidable for-loops that are in critical parts of the code, you may want to use a *just-in-time compiler* such as [numba](https://numba.pydata.org/). 

In [3]:
# A basic for-loop loops over a given range:
r = 10 # we want to count 0,1,2,...,9
for number in range(r):
    print(number)
    
print("\n============\n")

# A for-loop works for a collection of items in a list too:
def sample_func(): return None # initialise an arbitrary function
array = np.arange(25).reshape(5,5) # and an array
lst = [1,2,3,'a','dog','item',10.0,55.5,1e-6,sample_func,array]

for item in lst:
    print(item)

print("\n============\n")

# The enumerate function provides a pythonic way of looping over items and keeping count of the loop:
for index, item in enumerate(lst):
    print("index = %i, item = %s" %(index, str(item)))

0
1
2
3
4
5
6
7
8
9


1
2
3
a
dog
item
10.0
55.5
1e-06
<function sample_func at 0x7ff85c6b95f0>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


index = 0, item = 1
index = 1, item = 2
index = 2, item = 3
index = 3, item = a
index = 4, item = dog
index = 5, item = item
index = 6, item = 10.0
index = 7, item = 55.5
index = 8, item = 1e-06
index = 9, item = <function sample_func at 0x7ff85c6b95f0>
index = 10, item = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


-----

# List comprehensions
A powerful feature of Python is *list comprehension*. In the last tutorial, we were introduced to the basics of lists in Python. Now, we see how we can make use of list comprehensions to write compact code.

A common operation in Python is zipping. Say you have two lists, A and B, and you want to create a third list, C that has the first element of A with the first element of B, second element of A with the second element of B and so on. To do this, you use the `zip` function. Let's see how we can do this in a for-loop:

In [23]:
# Let's use the help of numpy to generate some random lists A and B:

# What does numpy.random.seed() do?
# Try commenting out this line below and re-run this cell multiple times. Print out the list A.
# What happens to the entries of A if the seed is enabled versus not specifying the seed?
np.random.seed(555)  
A = np.random.randint(0,1000,size=(8))
print("list A is: %s" %A)

# What is numpy.arange?
B = np.arange(100,108,1)
print("list B is: %s" %B)

# we create C as an empty list.
C = []

# now we loop through lists A and B and zip the items in the list together:
for zipped_item in zip(A,B):
    C.append(zipped_item)    
print("list C is: %s" %C)

# If we were to use list comprehension...
D = [zipped_item for zipped_item in zip(A,B)]
print("list D is: %s" %D)

list A is: [410 686  33 580 381 550 406 233]
list B is: [100 101 102 103 104 105 106 107]
list C is: [(410, 100), (686, 101), (33, 102), (580, 103), (381, 104), (550, 105), (406, 106), (233, 107)]
list D is: [(410, 100), (686, 101), (33, 102), (580, 103), (381, 104), (550, 105), (406, 106), (233, 107)]


You may have noticed that inside each list, the elements are now grouped pair-wise between (parenthesis) brackets, i.e. `()`. We know that lists are defined by the square brackets `[]`. These parenthesis are *not* lists, but tuples. If you do not already know, find out the difference between a list and a tuple.

Now let's play around a little more with the list D.

In [36]:
# Let's loop the entries in D. We see that each entry is a tuple!
# In other words, the size of list D is actually 8 rows by 2 columns, or 8x2.
print("the entries of the list D are:\n")
for idx, entry in enumerate(D):
    print("entry index %i is: %s" %(idx, entry))
    
print("")

# What if we want to "flatten" D? I.e. to make the list a flat list of 16 entries?
# Let's try it with list comprehension:
E = [item for item_pair in D for item in item_pair]
print("list E is: %s" %E)

the entries of the list D are:

entry index 0 is: (410, 100)
entry index 1 is: (686, 101)
entry index 2 is: (33, 102)
entry index 3 is: (580, 103)
entry index 4 is: (381, 104)
entry index 5 is: (550, 105)
entry index 6 is: (406, 106)
entry index 7 is: (233, 107)

list E is: [410, 100, 686, 101, 33, 102, 580, 103, 381, 104, 550, 105, 406, 106, 233, 107]



Try to make sense of the list comprehension for `E` above. How would you write it in terms of for-loops?

----

# Warning!

Python lists are different from numpy lists:

In [44]:
# We did the following the code above with a numpy list:
numpy_lst = np.arange(10)*0.1
# Let's see what the results are
print("the list numpy_t is: %s" %numpy_lst)

# On the other hand, if we were to muliply a Python list:
python_lst = [10]*10
print("the list python_t is: %s" %python_lst)

print("")
# To check the type of list you have,
print(type(numpy_lst))
print(type(python_lst))

print("")
# To convert a python list to a numpy list:
new_numpy_lst = np.array(python_lst)
print(type(new_numpy_lst))

# And to convert a numpy list to a python list:
new_python_lst = list(numpy_lst)
print(type(new_python_lst))

the list numpy_t is: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
the list python_t is: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

<class 'numpy.ndarray'>
<class 'list'>

<class 'numpy.ndarray'>
<class 'list'>


There are a few other subtle differences between the two types of list. For example, Python lists can be just a collection of items, while numpy lists have stricter rules on what *types* its entries are.

In [47]:
# Let's initialise the Python list we have above:
def sample_func(): return None # initialise an arbitrary function
array = np.arange(25).reshape(5,5) # and an array
lst = [1,2,3,'a','dog','item',10.0,55.5,1e-6,sample_func,array]

# This is entirely valid as a Python list. However, if we were to convert it to a numpy list...
numpy_lst = np.array(lst)

/home/ray/anaconda3/envs/playground/lib/python3.7/site-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [48]:
# Numpy complains that the entries of the list are not of the same type.
# To tell numpy that the list is meant to contain entries of different types, we need to explicitly specify that:
numpy_lst_ok = np.array(lst, dtype='object')